#!/bin/bash

###############################################################################
#
# Copyright 2023 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################

set -ex

LANG=C
SDIR="/root/workspace"
BFB="${BFB:-/lib/firmware/mellanox/boot/default.bfb}"
CAPSULE="${CAPSULE:-/lib/firmware/mellanox/boot/capsule/boot_update2.cap}"
KERNEL_DBG_ARGS="ignore_loglevel"
verbose=0
kdir=$(/bin/ls -1d /lib/modules/4.19* /lib/modules/4.20* /lib/modules/5.* 2> /dev/null | head -1)
if [ -n "$kdir" ]; then
    kernel=${kdir##*/}
else
    kernel=$(/bin/ls -1 /lib/modules/ | head -1)
fi

usage() {
cat << EOF
Usage: $(basename $0) [ OPTIONS ]
OPTIONS:
-k, -kernel,         --kernel <kernel version>  Kernel version for the SmartNIC. Default: $kernel
-v, -verbose,   --verbose                       Run script in verbose mode. Will print out each step of execution.
-h, -help,      --help                          Display help


EOF
}

options=$(getopt -l "kernel:,help,verbose" -o "k:hv" -a -- "$@")

eval set -- "$options"

while true
do
        case $1 in
                -h|--help)
                    usage
                    exit 0
                    ;;
                -k|--kernel)
                    shift
                    kernel=$1
                    ;;
                -v|--verbose)
                    verbose=1
                    set -xv
                    ;;
                --)
                    shift
                    break;;
        esac
        shift
done

bootctl_module="mlxbf-bootctl"

modinfo -n -k $kernel "mlx-bootctl" > /dev/null 2>&1 && bootctl_module="mlx-bootctl"

SCRIPTS_DIR=$(dirname $0)

WDIR=${WDIR:-/root/workspace/bfb}

echo "Work directory: $WDIR"

ID=$(grep ^ID= /etc/os-release | cut -d= -f2 | tr -d '"')
VERSION=$(grep ^VERSION= /etc/os-release | cut -d= -f2 | tr -d '"')

BFB_FILENAME="${ID}-${VERSION}.bfb"

PATH=$PATH:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/mellanox/scripts:/opt/mellanox/scripts/bin
mkbfb=$(which mlx-mkbfb)

if [ ! -x "${mkbfb}" ]; then
	echo "- ERROR: mlx-mkbfb is required to build BFB image"
	exit 1
fi

if [[ ! -n "${BFB}" || ! -e "${BFB}" ]]; then
	echo "- ERROR: BFB was not found"
	exit 1
fi

# Fix python shabang from bfscripts
for f in $(rpm -ql mlxbf-bfscripts); do
	if [ -f $f ] && (head -1 $f | grep -q '/usr/bin/python'); then
		pathfix.py -i '/usr/bin/python' -pk $f
	fi
done

/bin/rm -rf ${WDIR}
mkdir -p ${WDIR}
cd ${WDIR}
/bin/rm -rf initramfs

initramfs=$WDIR/dump-initramfs-v0

dracut --no-hostonly -m "bash network base systemd systemd-initrd dracut-systemd shutdown udev-rules" \
	--add-drivers "${bootctl_module} sdhci-of-dwcmshc mlxbf_tmfifo dw_mmc_bluefield mmc_block virtio_console mlx5_core mlx5_ib mlxfw ib_umad nvme gpio-mlxbf2 gpio-mlxbf3 mlxbf-gige pinctrl-mlxbf3 8021q vitesse" \
	--filesystems "xfs fat vfat ext4" --gzip $initramfs ${kernel}

rm -f /etc/udev/rules.d/91-tmfifo_net.rules /etc/udev/rules.d/92-oob_net.rules

cat > /etc/default/grub << EOF
GRUB_TIMEOUT=0
GRUB_RECORDFAIL_TIMEOUT=2
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL=console
GRUB_SERIAL_COMMAND="serial --unit=1"
GRUB_CMDLINE_LINUX="crashkernel=auto console=hvc0 console=ttyAMA0 earlycon=pl011,0x13010000 $KERNEL_DBG_ARGS"
GRUB_DISABLE_RECOVERY="true"
GRUB_TIMEOUT_STYLE=countdown
GRUB_DISABLE_OS_PROBER=false
GRUB_DISABLE_LINUX_UUID=false
EOF

case "$(file --brief --mime-type "$initramfs")" in
    "application/x-lzma")
        cat_initrd="lzcat" ;;
    "application/x-lz4")
        cat_initrd="lz4cat" ;;
    *)
        cat_initrd="zcat" ;;
esac

echo "Rebuilding $initramfs"

mkdir -p ${WDIR}/initramfs
cd initramfs
$cat_initrd "$initramfs" | cpio -i

copy_bin()
{
    if [ -e $1 ]; then
        bin=$1
    else
        bin=$(which $1 2> /dev/null)
    fi
    if [ -z "$bin" ]; then
        echo "ERROR: Cannot find $1"
        return 1
    fi
    mkdir -p .$(dirname $bin)
    if [ -e .${bin} ]; then
        /bin/rm -f .${bin}
    fi
    cp -a $bin .${bin}

    # Copy dependencies
    for lib in $(ldd $bin 2> /dev/null | grep '=>' | awk '{print $3}' | grep -v '(0x0')
    do
        if [ -e .$lib ]; then
            continue
        fi
        mkdir -p .$(dirname $lib)
        cp -a $lib .$lib
        if [ -h $lib ]; then
            tlib=$(readlink -f $lib)
            if [ ! -e .$tlib ]; then
                mkdir -p .$(dirname $tlib)
                cp $tlib .$tlib
            fi
        fi
    done
}

copy_rpm()
{
    package=$1

    if ! (rpm -q $package); then
        # XXX: DOCA packages will make this fail
        # yum install -y $package || return
	echo WARNING: package $package not installed
	return
    fi

    case $package in
        chkconfig)
            for f in $(rpm -ql $package | grep -v share)
            do
                if [ -d $f ]; then
                    mkdir -p .${f}
                else
                    copy_bin $f
                fi
            done
            ;;
        *mft*)
            for f in $(rpm -ql $package | grep -v man)
            do
                if [ -d $f ]; then
                    continue
                fi
                copy_bin $f
            done
            ;;
        *)
            for f in $(rpm -ql $package | grep -vE 'share|build-id')
            do
                if [ -d $f ]; then
                    continue
                fi
                copy_bin $f
            done
            ;;
    esac
}

# Copy the content of RPM packages
for package in mlxbf-bfscripts util-linux dosfstools e2fsprogs kmod pciutils usbutils chkconfig mft mft-oem kernel-mft kmod-kernel-mft-mlnx tar xfsprogs coreutils nvme-cli mmc-utils parted which curl openssl gawk lvm2-libs device-mapper lvm2 iputils sshpass openssh-clients gzip $ADDON_RPMS
do
    copy_rpm $package || true
done

# Copy tools
for tool in xz efibootmgr bash getopt hexdump mstflint lspci perl \
        lsblk shutdown systemctl strings du free \
        mlxbf-bootctl id grep jq $ADDON_TOOLS
do
    if [ -d $tool ]; then
        continue
    fi
    copy_bin $tool
done

depmod -a -b ./ $kernel
ldconfig -r ./
mkdir -p usr/share/hwdata/ bin/
cp /usr/share/hwdata/pci.ids ./usr/share/hwdata/
mkdir -p ./lib/firmware/mellanox/boot/
cp /lib/firmware/mellanox/boot/default.bfb ./lib/firmware/mellanox/boot/default.bfb
cp -a /lib/firmware/mellanox/boot/capsule ./lib/firmware/mellanox/boot/
cp $CAPSULE ./lib/firmware/mellanox/boot/capsule/
mkdir -p mnt

if [ -d ${SDIR}/BF3BMC/ ]; then
	/bin/rm -rf BF3BMC
	if (grep -q prod /etc/mlnx-release); then
		cp -a ${SDIR}/BF3BMC/pk ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
	elif (grep -q dev /etc/mlnx-release); then
		cp -a ${SDIR}/BF3BMC/dk ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
	else
		cp -a ${SDIR}/BF3BMC/qp ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
	fi
	[ -d ${SDIR}/BF3BMC/golden_images ] && cp -a ${SDIR}/BF3BMC/golden_images ./BF3BMC
fi

if [ -d ${SDIR}/BF2BMC/ ]; then
	/bin/rm -rf BF2BMC
	if (grep -q prod /etc/mlnx-release); then
		cp -a ${SDIR}/BF2BMC/pk ./BF2BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
	else
		cp -a ${SDIR}/BF2BMC/qp/ ./BF2BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
	fi
fi

mkdir -p rhcos
# Tar the image
# export XZ_OPT="--threads=0 -9 --verbose" 
export XZ_OPT="--threads=0 -0 --verbose" 
tar -cJp \
    --exclude='./workspace' \
    --exclude='./signing-local' \
    --exclude='./signing-shared' \
    --exclude='./var/run/docker.sock' \
    --exclude='./root/workspace' \
    --exclude='./tmp/*' \
    --exclude='./run/*' \
    --exclude='./sys/*' \
    --exclude='./proc/*' \
    --exclude='./dev/*' \
    --exclude='./.dockerenv' \
    --exclude='./root/rpmbuild' \
    --exclude='./root/.rpmmacros' \
    --exclude='./root/.bash_history' \
    --exclude='./var/tmp/*rpm' \
    --exclude='./bin/qemu-aarch64-static' \
    --exclude='./usr/bin/qemu-aarch64-static' \
    --exclude='./usr/bin/qemu-arm-static' \
    --exclude='./var/lib/yum/*' \
    --exclude='./var/cache/yum/*' \
    -f "/tmp/image.tar.xz" \
    -C / .

mv /tmp/image.tar.xz rhcos/image.tar.xz

install -m 0755 ${SDIR}/install.sh ./rhcos/install.sh
# cp ${SDIR}/rhcos.raw.gz ./rhcos/
cp -a ${SDIR}/install.env ./rhcos/

mkdir scripts
cat > scripts/initrd-install << EOF
#!/bin/sh

echo
echo "==========================================" | tee /dev/kmsg
echo "Installing Red Hat CoreOS. Please wait... " | tee /dev/kmsg
echo "==========================================" | tee /dev/kmsg

modprobe -a sdhci-of-dwcmshc mlxbf_tmfifo mlxbf_gige vitesse pinctrl-mlxbf3 8021q dw_mmc_bluefield mmc_block virtio_console nvme ${bootctl_module} 2>&1 | tee /dev/kmsg
modprobe -a mlx5_ib mlxfw ib_umad 2>&1 | tee /dev/kmsg

sleep 5

/bin/sh /rhcos/install.sh
if [ \$? -eq 0 ]; then
        echo "===================================" | tee /dev/kmsg
        echo "Installation finished. Rebooting..." | tee /dev/kmsg
        echo "===================================" | tee /dev/kmsg
        echo
	reboot -f
else
        echo "================================" | tee /dev/kmsg
        echo "Failed to install Red Hat CoreOS" | tee /dev/kmsg
        echo "================================" | tee /dev/kmsg
fi
EOF

chmod +x scripts/initrd-install

cat > usr/lib/systemd/system/install-rhcos.service << EOF
[Unit]
Description=Install Red Hat CoreOS
After=initrd-root-fs.target initrd-parse-etc.service
After=dracut-initqueue.service dracut-mount.service

[Service]
Type=oneshot
ExecStart=/scripts/initrd-install
StandardInput=null
StandardOutput=syslog
StandardError=syslog+console
EOF

ln -s /usr/lib/systemd/system/install-rhcos.service etc/systemd/system/initrd.target.wants/install-rhcos.service

# Make initramfs
find . | cpio -H newc -o | gzip -9 > $initramfs

# Make bfb
cd ..
if [ ! -e $CAPSULE ]; then
    echo "ERROR: Capsule file $CAPSULE does not exist"
    exit 1
fi

boot_args=$(mktemp)
boot_args2=$(mktemp)
boot_path=$(mktemp)
boot_desc=$(mktemp)
printf "console=ttyAMA1 console=hvc0 console=ttyAMA0 earlycon=pl011,0x01000000 earlycon=pl011,0x01800000 initrd=initramfs" > \
    "$boot_args"
printf "console=hvc0 console=ttyAMA0 earlycon=pl011,0x13010000 initrd=initramfs $KERNEL_DBG_ARGS" > \
	"$boot_args2"

printf "VenHw(F019E406-8C9C-11E5-8797-001ACA00BFC4)/Image" > "$boot_path"
printf "Linux from rshim" > "$boot_desc"
vmlinuz=$WDIR/vmlinuz
if [ -e $SDIR/vmlinuz ]; then
    zcat $SDIR/vmlinuz > "$vmlinuz"
elif [ -e /boot/vmlinuz-$kernel ]; then
    zcat /boot/vmlinuz-$kernel > "$vmlinuz"
else
    zcat /lib/modules/$kernel/vmlinuz > "$vmlinuz"
fi

mkdir -p /workspace

$mkbfb \
    --image "$vmlinuz" --initramfs "$initramfs" \
    --capsule "$CAPSULE" \
    --boot-args-v0 "$boot_args" \
    --boot-args-v2 "$boot_args2" \
    --boot-path "$boot_path" \
    --boot-desc "$boot_desc" \
    ${BFB} /workspace/${BFB_FILENAME}
cd ..

echo "BFB is ready: $(readlink -f /workspace/${BFB_FILENAME})"
